name: First workflow
on: workflow_dispatch # Manually trigger workflows
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World"
      - name: print good bye
        run: echo "good bye"
